### ISSUE TITLE
Template Review Feedback

### ISSUE THREAD

**Issue by delsonting** [BianoCZ/pixel-gtm-template#1]
Your template has been approved for the gallery and should be live in the next day. Two recommendations:

1. The documentation link (https://pixel.biano.cz/pdf/GUIDE-GTM.pdf) in metadata.yaml is invalid, please publish the documentation (or update/remove the field)

2. You may want to use a drop down input for domain rather than free text as there is a discrete set of possible values for users to choose from and are less likely to enter an incorrect value.

**Comment by bagr001** [comment]
Thank you for approval and review. 

1. The documentation linkis now functional.
2. The domain is encoded in token we provide to our clients, so there is no need for special dropdown.
